steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mega-visa-tool:${SHORT_SHA:-latest}', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mega-visa-tool:${SHORT_SHA:-latest}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mega-visa-tool'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mega-visa-tool:${SHORT_SHA:-latest}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '300'
      - '--set-secrets'
      - 'ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,PERPLEXITY_API_KEY=PERPLEXITY_API_KEY:latest,LLAMA_CLOUD_API_KEY=LLAMA_CLOUD_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,MISTRAL_API_KEY=MISTRAL_API_KEY:latest,NEXT_PUBLIC_SUPABASE_URL=NEXT_PUBLIC_SUPABASE_URL:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,SENDGRID_API_KEY=SENDGRID_API_KEY:latest,SENDGRID_FROM_EMAIL=SENDGRID_FROM_EMAIL:latest,SENDGRID_REPLY_TO_EMAIL=SENDGRID_REPLY_TO_EMAIL:latest,API2PDF_API_KEY=API2PDF_API_KEY:latest,INNGEST_SIGNING_KEY=INNGEST_SIGNING_KEY:latest,INNGEST_EVENT_KEY=INNGEST_EVENT_KEY:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,MAX_FILES_PER_CASE=30,MAX_FILE_SIZE_MB=50,MAX_URLS_PER_CASE=100'

images:
  - 'gcr.io/$PROJECT_ID/mega-visa-tool:${SHORT_SHA:-latest}'

options:
  logging: CLOUD_LOGGING_ONLY
